name = "shipspark"
main = "src/index.tsx"
compatibility_date = "2026-02-21"

routes = [
  { pattern = "shipspark.net", custom_domain = true, zone_name = "shipspark.net" }
]

[vars]
X_SEARCH_QUERY = "#ShipSpark -is:retweet"

[triggers]
crons = ["*/15 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "shipspark"
database_id = "fb35bdf9-7b58-4e90-b946-066c8df58e58"
migrations_dir = "drizzle"
